#!/bin/bash

TESTS=$PWD
ROOT=$PWD/..
DEP="$ROOT/dep.py -v"
TMP_DIR=$TESTS/tmp
TMP_REPOS=$TMP_DIR/repos

test_title()
{
    echo
    echo "================================================================================"    
    echo "Running test \"$0\""
    echo "================================================================================"
    echo
}

test_echo()
{
    echo "### $@"
}

test_fail()
{
    test_echo "TEST FAIL: $@"
    exit 1
}

test_exec()
{
    test_echo "Test execute \"$@\""
    "$@"    
    status=$?
    if [[ $status -ne 0 ]]; then
	test_fail "FAIL: returned non-zero status $status"
    fi
}

test_file_exists()
{
    local file="$1"    
    test_echo "Test file exists \"$file\""
    if [[ ! -f "$file" ]]; then
	test_fail "FAIL: file \"$file\" does not exist"
    fi
}

test_file_contains()
{
    local file="$1"
    local expected="$2"
    local expected_file="expected-$file"
    test_file_exists "$file"
    test_echo "Test file \"$file\" contains expected result"
    rm -f "$expected_file"
    echo -n -e "$expected" > "$expected_file"
    diff -c "$expected_file" "$file"
    status=$?
    if [[ $status -ne 0 ]]; then
	test_fail "file \"$file\" does not contain expected result"
    fi
}

test_repo_path()
{
    echo "$TMP_REPOS/$1"
}

test_repo_url()
{
    local path=$(test_repo_path "$1")
    echo "file:///$path"
}

test_repo_git_dir()
{
    local path=$(test_repo_path "$1")
    echo "$path.git"
}

test_create_repo()
{
    local name="$1"
    test_echo "Create repository $name"
    local path=$(test_repo_path $name)
    local git_dir=$(test_repo_git_dir $name)
    local url=$(test_repo_url $name)
    test_exec git init --bare "$git_dir"
    test_exec git clone "$url" "$path"
    cd "$path"
    test_exec touch "FILE-$name"
    test_exec git add "FILE-$name"
    test_exec git commit -m "Initial commit on $name"
    test_exec git push
    cd -
}

# All tests run in temporary directory
if [[ -d $TMP_DIR ]]; then
    rm -rf $TMP_DIR
fi
mkdir -p $TMP_DIR
mkdir -p $TMP_REPOS
cd $TMP_DIR
