#!/bin/bash

TESTS=$PWD
ROOT=$PWD/..
DEP="$ROOT/dep.py -v"
TEST_NAME="$(basename $0)"
TMP_DIR=$TESTS/tmp/$TEST_NAME
TMP_WORK=$TMP_DIR/work
TMP_REPOS=$TMP_DIR/repos

test_title()
{
    echo
    echo "================================================================================"    
    echo "Running test \"$TEST_NAME\""
    echo "================================================================================"
    echo
}

test_echo()
{
    echo "### $@"
}

test_fail()
{
    local file="$TEST_NAME"
    local line="${BASH_LINENO[1]}"
    echo "$file:$line: TEST FAIL: $@"
    exit 1
}

test_exec()
{
    test_echo "Test execute \"$@\""
    "$@"    
    status=$?
    if [[ $status -ne 0 ]]; then
	test_fail "FAIL: returned non-zero status $status"
    fi
}

test_exec_fails()
{
    test_echo "Test execute which should fail \"$@\""
    "$@"    
    status=$?
    if [[ $status -eq 0 ]]; then
	test_fail "FAIL: returned zero status"
    fi
}

test_file_exists()
{
    local file="$1"    
    test_echo "Test file exists \"$file\""
    if [[ ! -f "$file" ]]; then
	test_fail "FAIL: file \"$file\" does not exist"
    fi
}

test_file_contains()
{
    local file="$1"
    local expected="$2"
    test_file_exists "$file"
    test_echo "Test file \"$file\" contains expected result"
    echo -n -e "$expected" | diff -c - "$file"
    status=$?
    if [[ $status -ne 0 ]]; then
	test_fail "file \"$file\" does not contain expected result"
    fi
}

test_dir_exists()
{
    local dir="$1"    
    test_echo "Test dir exists \"$dir\""
    if [[ ! -d "$dir" ]]; then
	test_fail "dir \"$dir\" does not exist"
    fi
}

test_repo_path()
{
    echo "$TMP_REPOS/$1"
}

test_repo_url()
{
    local path=$(test_repo_path "$1")
    echo "file:///$path"
}

test_repo_git_dir()
{
    local path=$(test_repo_path "$1")
    echo "$path.git"
}

test_git_create_repo()
{
    local name="$1"
    test_echo "Create repository $name"
    local path=$(test_repo_path $name)
    local git_dir=$(test_repo_git_dir $name)
    local url=$(test_repo_url $name)
    test_exec git init --bare "$git_dir"
    test_exec git clone "$url" "$path"
    cd "$path"
    test_exec touch "FILE-$name"
    test_exec git add "FILE-$name"
    test_exec git commit -m "Initial commit on $name"
    test_exec git push
    cd -
}

test_git_status_equals()
{
    local expected="$1"
    test_echo "Test git status matches expected result"
    echo -n -e "$expected" | diff -c - <(git status -sb | sed -e '/^#/d')
    status=$?
    if [[ $status -ne 0 ]]; then
	test_fail "git status does not match expected result"
    fi
}   

test_title

# All tests run in temporary directory
if [[ -d $TMP_DIR ]]; then
    rm -rf $TMP_DIR
fi
mkdir -p $TMP_WORK
mkdir -p $TMP_REPOS
cd $TMP_WORK

