#!/bin/bash
. helpers
test_exec git init
test_dir_exists .git
test_exec $DEP init
test_file_contains .depconfig "[core]
	default-dep-dir = dep
"
test_git_create_repo TOP
url=$(test_repo_url TOP)
commit=$(test_repo_git_commit TOP)
test_exec $DEP add "$url"
test_file_contains .depconfig "[core]
	default-dep-dir = dep

[dep \"TOP\"]
	relpath = dep/TOP
	url = $url
	vcs = git
	branch = refs/heads/master
	commit = $commit
"
test_git_status_equals "A  .depconfig
A  .gitignore
"

