#!/bin/bash
. helpers
test_title
rm -f .depconfig
test_exec $DEP init
test_file_contains .depconfig "[core]\n\tdefault-dep-dir = dep\n"
test_create_repo TOP
url=$(test_repo_url TOP)
test_exec $DEP add "$url"
test_file_contains .depconfig "[core]\n\tdefault-dep-dir = dep\n\n[dep \"thing\"]\n\trelpath = dep/TOP\n\turl = $url\n\tvcs = git\n"
