#!/bin/bash
. helpers
root="$PWD"
cd $root/..
test_exec_fails $DEP config --root-work-dir
test_exec_fails $DEP config --work-dir
cd $root
touch .depconfig
test_output_from_exec "$root\n" $DEP config --root-work-dir
test_output_from_exec "$root\n" $DEP config --work-dir
mkdir B
cd B
touch .depconfig
test_output_from_exec "$root\n" $DEP config --root-work-dir
test_output_from_exec "$root/B\n" $DEP config --work-dir
mkdir -p C/D
cd C/D
touch .depconfig
test_output_from_exec "$root\n" $DEP config --root-work-dir
test_output_from_exec "$root/B/C/D\n" $DEP config --work-dir
cd $root

