#!/bin/bash
. helpers
test_exec $DEP init
test_file_contains .depconfig "[core]
	default-dep-dir = dep
"
test_git_create_repo TOP
url=$(test_repo_url TOP)
test_exec $DEP add "$url"
test_file_contains .depconfig "[core]
	default-dep-dir = dep

[dep \"TOP\"]
	relpath = dep/TOP
	url = $url
	vcs = git
"
